name: spot-cli # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A command line interface to control the Spotify client # 79 char long summary
description: |
  This is a command line interface to control the Spotify client. A few  
  of the features are Play, Pause, and skip tracks and display artistist info
  right from the command line. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  spot-cli:
    command: bin/spot_cli

parts:
  spot-cli:
    source: https://github.com/jmcs811/spot-cli/releases/download/1.1-release/spotify-cli-1.1.tar.gz
    plugin: autotools
    build-packages:
      - gcc
      - make
      - autoconf
      - libdbus-1-dev
      - dbus
    stage-packages:
      - dbus
